name: epos
channels:
  - defaults
dependencies:
  - python=3.6
  - anaconda
  - numpy=1.16.6
  - tensorflow-gpu=1.12.0
  - opencv=3.4.2
  - tabulate=0.8.3
  - imageio=2.9.0
  - mjirik::pypng=0.0.18
  - conda-forge::igl
  - glog=0.4.0
